In [32]:
import pandas as pd
import datetime

pd.set_option('display.max_columns', 85)

In [33]:

df_original = pd.read_csv('data/redin_county_data_2023_05_14.tsv', sep='\t')

In [34]:
df_copy = df_original.copy()

In [35]:
df_copy

,period_begin,period_end,period_duration,region_type,region_type_id,table_id,is_seasonally_adjusted,region,city,state,state_code,property_type,property_type_id,median_sale_price,median_sale_price_mom,median_sale_price_yoy,median_list_price,median_list_price_mom,median_list_price_yoy,median_ppsf,median_ppsf_mom,median_ppsf_yoy,median_list_ppsf,median_list_ppsf_mom,median_list_ppsf_yoy,homes_sold,homes_sold_mom,homes_sold_yoy,pending_sales,pending_sales_mom,pending_sales_yoy,new_listings,new_listings_mom,new_listings_yoy,inventory,inventory_mom,inventory_yoy,months_of_supply,months_of_supply_mom,months_of_supply_yoy,median_dom,median_dom_mom,median_dom_yoy,avg_sale_to_list,avg_sale_to_list_mom,avg_sale_to_list_yoy,sold_above_list,sold_above_list_mom,sold_above_list_yoy,price_drops,price_drops_mom,price_drops_yoy,off_market_in_two_weeks,off_market_in_two_weeks_mom,off_market_in_two_weeks_yoy,parent_metro_region,parent_metro_region_metro_code,last_updated
0,2023-02-01,2023-02-28,30,county,5,2429,f,"Kent County, RI",NaN,Rhode Island,RI,Multi-Family (2-4 Unit),4,377000.0,0.256667,-0.020779,359000.0,0.028653,0.071642,151.261284,0.080324,0.165409,223.333333,0.004012,0.030671,4.0,-0.428571,-0.666667,8.0,1.000000,-0.384615,8.0,-0.333333,-0.384615,20.0,-0.130435,0.052632,5.0,1.7,3.4,97.0,86.0,63.0,0.973341,-0.011071,-0.022020,0.500000,0.071429,0.166667,0.250000,0.163043,0.197368,0.500000,0.500000,-0.115385,"Providence, RI",39300.0,2023-04-09 14:55:08
1,2022-04-01,2022-04-30,30,county,5,519,f,"Bulloch County, GA",NaN,Georgia,GA,All Residential,-1,210000.0,-0.094828,-0.009200,239995.0,-0.076765,0.170707,135.015130,0.000056,0.240334,141.615620,-0.015304,0.254727,99.0,-0.116071,0.164706,102.0,-0.055556,-0.089286,87.0,-0.360294,-0.382979,149.0,-0.123529,0.146154,1.5,0.0,0.0,19.0,-9.0,1.0,1.006817,0.020355,0.022923,0.333333,0.002976,0.062745,0.053691,0.000750,-0.000155,0.441176,-0.086601,-0.237395,"Statesboro, GA",44340.0,2023-04-09 14:55:08
2,2019-05-01,2019-05-31,30,county,5,1115,f,"Bath County, KY",NaN,Kentucky,KY,All Residential,-1,159500.0,0.386957,0.463303,99900.0,-0.371698,0.148276,96.260684,0.464836,1.048851,83.042394,-0.122571,0.721533,4.0,-0.200000,0.333333,8.0,7.000000,0.333333,7.0,0.000000,-0.363636,24.0,-0.111111,0.090909,6.0,0.6,-1.3,60.0,-156.0,7.0,0.914713,-0.042792,0.022840,0.000000,0.000000,0.000000,0.166667,-0.129630,-0.151515,0.250000,0.250000,0.083333,"Mount Sterling, KY",34460.0,2023-04-09 14:55:08
3,2018-11-01,2018-11-30,30,county,5,2455,f,"Greenville County, SC",NaN,South Carolina,SC,All Residential,-1,220000.0,0.009174,0.067961,230000.0,0.022222,0.070265,110.350076,0.000383,0.070188,113.383743,-0.025587,0.040978,632.0,0.004769,0.051581,473.0,0.039560,-0.006303,604.0,-0.210458,-0.075038,2320.0,-0.066398,-0.006424,3.7,-0.3,-0.2,62.0,1.0,3.0,0.981236,0.004272,0.000512,0.166139,-0.013511,-0.040184,0.196983,-0.058953,0.032957,0.141649,-0.020988,-0.011712,"Greenville, SC",24860.0,2023-04-09 14:55:08
4,2017-11-01,2017-11-30,30,county,5,3078,f,"Cowlitz County, WA",NaN,Washington,WA,Multi-Family (2-4 Unit),4,200000.0,0.481481,0.198681,234900.0,0.044464,0.180405,116.959064,0.268356,0.144063,148.670886,-0.011625,0.167397,1.0,-0.500000,-0.750000,5.0,1.500000,4.000000,1.0,-0.750000,-0.750000,6.0,-0.400000,-0.250000,6.0,1.0,4.0,9.0,-4.0,-8.0,0.952381,-0.011905,-0.024879,0.000000,0.000000,0.000000,NaN,NaN,NaN,0.200000,-0.800000,0.200000,"Longview, WA",31020.0,2023-04-09 14:55:08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
863944,2015-03-01,2015-03-31,30,county,5,1628,f,"Dade County, MO",NaN,Missouri,MO,Single Family Residential,6,105000.0,NaN,0.400000,NaN,NaN,NaN,46.875000,NaN,-0.091875,NaN,NaN,NaN,1.0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,0.000000,2.0,NaN,0.0,212.0,NaN,-94.0,1.000000,NaN,0.144812,0.000000,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,Missouri nonmetropolitan area,NaN,2023-04-09 14:55:08
863945,2021-04-01,2021-04-30,30,county,5,809,f,"Whiteside County, IL",NaN,Illinois,IL,Condo/Co-op,3,72500.0,-0.635678,NaN,98400.0,0.109357,NaN,61.266760,-0.322408,NaN,71.728587,0.062073,NaN,4.0,1.000000,NaN,NaN,NaN,NaN,1.0,-0.500000,NaN,3.0,0.500000,NaN,0.8,-0.2,NaN,230.0,105.0,NaN,0.993886,0.033557,NaN,0.500000,0.500000,NaN,0.333333,NaN,NaN,NaN,NaN,NaN,"Sterling, IL",44580.0,2023-04-09 14:55:08
863946,2017-10-01,2017-10-31,30,county,5,2200,f,"Jefferson County, OH",NaN,Ohio,OH,Condo/Co-op,3,160000.0,NaN,0.882353,96900.0,NaN,NaN,88.888889,NaN,0.171242,72.249512,NaN,NaN,1.0,NaN,0.000000,1.0,NaN,0.000000,1.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,72.0,NaN,22.0,0.941730,NaN,0.046051,0.000000,NaN,0.000000,NaN,NaN,NaN,0.000000,NaN,0.000000,"Weirton, WV",48260.0,2023-04-09 14:55:08
863947,2015-06-01,2015-06-30,30,county,5,2443,f,"Cherokee County, SC",NaN,South Carolina,SC,Single Family Residential,6,201500.0,NaN,NaN,19900.0,NaN,NaN,94.213859,NaN,NaN,13.857939,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,12.0,NaN,NaN,6.0,NaN,NaN,315.0,NaN,NaN,0.980121,NaN,NaN,0.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Gaffney, SC",23500.0,2023-04-09 14:55:08
863948,2022-09-01,2022-09-30,30,county,5,2899,f,"Davis County, UT",NaN,Utah,UT,Multi-Family (2-4 Unit),4,552000.0,-0.283117,-0.157252,514900.0,-0.009712,0.072708,257.464789,0.346173,0.265749,216.417910,-0.030007,0.053633,3.0,0.000000,-0.571429,1.0,-0.800000,-0.800000,1.0,-0.800000,-0.800000,6.0,0.000000,0.200000,2.0,0.0,1.3,29.0,-10.0,2.0,0.970678,-0.012586,0.016162,0.333333,0.333333,0.333333,0.500000,0.333333,0.300000,0.000000,-0.200000,-0.600000,"Ogden, UT",36260.0,2023-04-09 14:55:08

In [36]:
df = df_copy.loc[:, ['period_begin', 'region', 'state', 'state_code', 'property_type', 'homes_sold', 'new_listings', 'inventory', 'median_dom', 'months_of_supply', 'avg_sale_to_list', 'last_updated']]

In [37]:
df = df.sort_values(by='period_begin', ascending=False)
df = df.reset_index(drop=True)
df = df.rename(columns={'region':'county', 'period_begin': 'month'})
df

,month,county,state,state_code,property_type,homes_sold,new_listings,inventory,median_dom,months_of_supply,avg_sale_to_list,last_updated
0,2023-03-01,"Iron County, MI",Michigan,MI,All Residential,16.0,7.0,34.0,131.0,2.1,0.940495,2023-04-09 14:55:08
1,2023-03-01,"McLeod County, MN",Minnesota,MN,Townhouse,2.0,2.0,2.0,161.0,1.0,0.991800,2023-04-09 14:55:08
2,2023-03-01,"Dorchester County, SC",South Carolina,SC,Single Family Residential,287.0,321.0,699.0,65.0,2.4,0.989761,2023-04-09 14:55:08
3,2023-03-01,"Grundy County, IL",Illinois,IL,Single Family Residential,42.0,47.0,98.0,62.0,2.3,1.002184,2023-04-09 14:55:08
4,2023-03-01,"Wexford County, MI",Michigan,MI,All Residential,35.0,34.0,60.0,66.0,1.7,0.988345,2023-04-09 14:55:08
...,...,...,...,...,...,...,...,...,...,...,...,...
863944,2012-01-01,"Shoshone County, ID",Idaho,ID,Single Family Residential,15.0,24.0,113.0,115.0,7.5,0.860946,2023-04-09 14:55:08
863945,2012-01-01,"Green Lake County, WI",Wisconsin,WI,Condo/Co-op,1.0,NaN,7.0,913.0,7.0,0.952736,2023-04-09 14:55:08
863946,2012-01-01,"Merrimack County, NH",New Hampshire,NH,Condo/Co-op,13.0,6.0,42.0,155.0,3.2,0.930686,2023-04-09 14:55:08
863947,2012-01-01,"Massac County, IL",Illinois,IL,All Residential,4.0,10.0,112.0,431.0,28.0,0.872810,2023-04-09 14:55:08
863948,2012-01-01,"King County, WA",Washington,WA,Multi-Family (2-4 Unit),16.0,30.0,140.0,90.0,8.8,0.968432,2023-04-09 14:55:08

In [38]:
# Convert the 'month' column to a datetime object
df['month'] = pd.to_datetime(df['month'])
df['county_name'] = df['county'].apply(lambda x: x.split(',')[0] if ',' in x else x)

filtered_df = df[df['month'] >= '2022-01-01']
df_residential = filtered_df[filtered_df['property_type'] == 'All Residential']

df_residential

,month,county,state,state_code,property_type,homes_sold,new_listings,inventory,median_dom,months_of_supply,avg_sale_to_list,last_updated,county_name
0,2023-03-01,"Iron County, MI",Michigan,MI,All Residential,16.0,7.0,34.0,131.0,2.1,0.940495,2023-04-09 14:55:08,Iron County
4,2023-03-01,"Wexford County, MI",Michigan,MI,All Residential,35.0,34.0,60.0,66.0,1.7,0.988345,2023-04-09 14:55:08,Wexford County
8,2023-03-01,"Montgomery County, IN",Indiana,IN,All Residential,44.0,45.0,45.0,29.0,1.0,0.962447,2023-04-09 14:55:08,Montgomery County
9,2023-03-01,"Columbia County, NY",New York,NY,All Residential,49.0,66.0,250.0,119.0,5.1,0.952711,2023-04-09 14:55:08,Columbia County
11,2023-03-01,"Fredericksburg, VA",Virginia,VA,All Residential,25.0,23.0,43.0,20.0,1.7,1.000778,2023-04-09 14:55:08,Fredericksburg
...,...,...,...,...,...,...,...,...,...,...,...,...,...
117949,2022-01-01,"Yuma County, CO",Colorado,CO,All Residential,2.0,2.0,4.0,9.0,2.0,0.925862,2023-04-09 14:55:08,Yuma County
117954,2022-01-01,"Benton County, TN",Tennessee,TN,All Residential,3.0,8.0,12.0,105.0,4.0,0.909076,2023-04-09 14:55:08,Benton County
117956,2022-01-01,"Mono County, CA",California,CA,All Residential,44.0,48.0,106.0,58.0,2.4,1.007940,2023-04-09 14:55:08,Mono County
117960,2022-01-01,"McDonald County, MO",Missouri,MO,All Residential,8.0,11.0,37.0,75.0,4.6,NaN,2023-04-09 14:55:08,McDonald County
117963,2022-01-01,"Cochise County, AZ",Arizona,AZ,All Residential,158.0,156.0,336.0,56.0,2.1,0.981407,2023-04-09 14:55:08,Cochise County

In [39]:
df = df_residential.copy()

# Drop the 'county' and 'state' columns
df = df.drop(columns=['county', 'state'])

# Rearrange the columns
df = df[['month', 'county_name', 'state_code', 'property_type', 'homes_sold', 'new_listings', 'inventory', 
         'median_dom', 'months_of_supply', 'avg_sale_to_list', 'last_updated']]

df

,month,county_name,state_code,property_type,homes_sold,new_listings,inventory,median_dom,months_of_supply,avg_sale_to_list,last_updated
0,2023-03-01,Iron County,MI,All Residential,16.0,7.0,34.0,131.0,2.1,0.940495,2023-04-09 14:55:08
4,2023-03-01,Wexford County,MI,All Residential,35.0,34.0,60.0,66.0,1.7,0.988345,2023-04-09 14:55:08
8,2023-03-01,Montgomery County,IN,All Residential,44.0,45.0,45.0,29.0,1.0,0.962447,2023-04-09 14:55:08
9,2023-03-01,Columbia County,NY,All Residential,49.0,66.0,250.0,119.0,5.1,0.952711,2023-04-09 14:55:08
11,2023-03-01,Fredericksburg,VA,All Residential,25.0,23.0,43.0,20.0,1.7,1.000778,2023-04-09 14:55:08
...,...,...,...,...,...,...,...,...,...,...,...
117949,2022-01-01,Yuma County,CO,All Residential,2.0,2.0,4.0,9.0,2.0,0.925862,2023-04-09 14:55:08
117954,2022-01-01,Benton County,TN,All Residential,3.0,8.0,12.0,105.0,4.0,0.909076,2023-04-09 14:55:08
117956,2022-01-01,Mono County,CA,All Residential,44.0,48.0,106.0,58.0,2.4,1.007940,2023-04-09 14:55:08
117960,2022-01-01,McDonald County,MO,All Residential,8.0,11.0,37.0,75.0,4.6,NaN,2023-04-09 14:55:08
117963,2022-01-01,Cochise County,AZ,All Residential,158.0,156.0,336.0,56.0,2.1,0.981407,2023-04-09 14:55:08

In [40]:
# Get today's date
today = datetime.date.today()
date_string = today.strftime("%Y-%m-%d")
file_path = f"data/redfin_processed_output_{date_string}.csv"
df.to_csv(file_path, index=False)