In [43]:
import pandas as pd
import datetime

pd.set_option('display.max_columns', 85)

In [44]:

df_original = pd.read_csv('data/redfin_county_data.csv', sep='\t')

In [45]:
df_copy = df_original.copy()

In [46]:
df_copy

,period_begin,period_end,period_duration,region_type,region_type_id,table_id,is_seasonally_adjusted,region,city,state,state_code,property_type,property_type_id,median_sale_price,median_sale_price_mom,median_sale_price_yoy,median_list_price,median_list_price_mom,median_list_price_yoy,median_ppsf,median_ppsf_mom,median_ppsf_yoy,median_list_ppsf,median_list_ppsf_mom,median_list_ppsf_yoy,homes_sold,homes_sold_mom,homes_sold_yoy,pending_sales,pending_sales_mom,pending_sales_yoy,new_listings,new_listings_mom,new_listings_yoy,inventory,inventory_mom,inventory_yoy,months_of_supply,months_of_supply_mom,months_of_supply_yoy,median_dom,median_dom_mom,median_dom_yoy,avg_sale_to_list,avg_sale_to_list_mom,avg_sale_to_list_yoy,sold_above_list,sold_above_list_mom,sold_above_list_yoy,price_drops,price_drops_mom,price_drops_yoy,off_market_in_two_weeks,off_market_in_two_weeks_mom,off_market_in_two_weeks_yoy,parent_metro_region,parent_metro_region_metro_code,last_updated
0,2023-02-01,2023-02-28,30,county,5,2429,f,"Kent County, RI",NaN,Rhode Island,RI,Multi-Family (2-4 Unit),4,377000.0,0.256667,-0.020779,359000.0,0.028653,0.071642,151.261284,0.080324,0.165409,223.333333,0.004012,0.030671,4.0,-0.428571,-0.666667,8.0,1.000000,-0.384615,8.0,-0.333333,-0.384615,20.0,-0.130435,0.052632,5.0,1.7,3.4,97.0,86.0,63.0,0.973341,-0.011071,-0.022020,0.500000,0.071429,0.166667,0.250000,0.163043,0.197368,0.500000,0.500000,-0.115385,"Providence, RI",39300.0,2023-04-09 14:55:08
1,2022-04-01,2022-04-30,30,county,5,519,f,"Bulloch County, GA",NaN,Georgia,GA,All Residential,-1,210000.0,-0.094828,-0.009200,239995.0,-0.076765,0.170707,135.015130,0.000056,0.240334,141.615620,-0.015304,0.254727,99.0,-0.116071,0.164706,102.0,-0.055556,-0.089286,87.0,-0.360294,-0.382979,149.0,-0.123529,0.146154,1.5,0.0,0.0,19.0,-9.0,1.0,1.006817,0.020355,0.022923,0.333333,0.002976,0.062745,0.053691,0.000750,-0.000155,0.441176,-0.086601,-0.237395,"Statesboro, GA",44340.0,2023-04-09 14:55:08
2,2022-04-01,2022-04-30,30,county,5,1193,f,"Mercer County, KY",NaN,Kentucky,KY,Townhouse,13,342500.0,NaN,NaN,NaN,NaN,NaN,239.471511,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,0.5,NaN,NaN,4.0,NaN,NaN,0.984950,NaN,NaN,0.000000,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,Kentucky nonmetropolitan area,NaN,2023-04-09 14:55:08
3,2022-07-01,2022-07-31,30,county,5,3078,f,"Cowlitz County, WA",NaN,Washington,WA,Single Family Residential,6,381213.0,-0.023782,0.003324,425000.0,0.070664,0.183844,262.552521,0.012709,0.064021,242.022494,-0.065260,0.073391,147.0,0.204918,-0.032895,139.0,-0.079470,-0.114650,175.0,-0.150485,-0.011299,265.0,0.099585,0.802721,1.8,-0.2,0.8,10.0,-2.0,2.0,1.009263,0.004183,-0.017736,0.544218,0.027824,-0.028151,0.501887,0.028858,0.073315,0.467626,-0.154891,-0.245750,"Longview, WA",31020.0,2023-04-09 14:55:08
4,2022-02-01,2022-02-28,30,county,5,987,f,"Scott County, IA",NaN,Iowa,IA,Condo/Co-op,3,95000.0,-0.707405,NaN,NaN,NaN,NaN,164.075993,-0.269270,NaN,NaN,NaN,NaN,1.0,-0.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,0.000000,NaN,4.0,2.0,NaN,7725.0,7591.0,NaN,1.585977,0.580811,NaN,1.000000,0.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Davenport, IA",19340.0,2023-04-09 14:55:08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117964,2022-02-01,2022-02-28,30,county,5,2379,f,"Columbia County, PA",NaN,Pennsylvania,PA,Townhouse,13,179000.0,0.205387,-0.251046,184450.0,NaN,0.054000,116.688396,0.038373,-0.219799,124.461207,NaN,0.227811,1.0,-0.500000,0.000000,1.0,0.000000,NaN,1.0,NaN,0.000000,1.0,0.000000,-0.500000,1.0,0.5,-1.0,51.0,-35.0,-123.0,1.000000,-0.022201,0.003752,0.000000,-0.500000,0.000000,NaN,NaN,NaN,0.000000,0.000000,NaN,"Bloomsburg, PA",14100.0,2023-04-09 14:55:08
117965,2022-12-01,2022-12-31,30,county,5,3043,f,"Falls Church, VA",NaN,Virginia,VA,All Residential,-1,800000.0,0.111876,0.041667,762500.0,-0.175230,-0.244676,394.105552,0.240749,-0.071060,457.170533,0.066203,0.236017,5.0,-0.375000,-0.642857,5.0,0.000000,-0.500000,6.0,0.500000,0.000000,10.0,0.000000,-0.090909,2.0,0.7,1.2,33.0,-25.0,-19.0,0.984598,0.027759,-0.001517,0.200000,0.075000,-0.085714,0.300000,0.100000,0.118182,0.000000,0.000000,-0.300000,"Washington, DC",47894.0,2023-04-09 14:55:08
117966,2022-09-01,2022-09-30,30,county,5,1907,f,"Salem County, NJ",NaN,New Jersey,NJ,Multi-Family (2-4 Unit),4,225000.0,0.000000,0.666667,237500.0,0.055556,0.199798,81.437126,-0.319837,0.122023,139.942857,-0.069918,0.008904,3.0,-0.571429,0.000000,7.0,2.500000,-0.125000,5.0,0.666667,-0.166667,9.0,-0.307692,-0.666667,3.0,1.1,-6.0,52.0,-10.0,20.0,0.977339,0.111822,0.025325,0.000000,0.000000,0.000000,0.111111,-0.119658,-0.148148,0.285714,0.285714,-0.089286,"Wilmington, DE",48864.0,2023-04-09 14:55:08
117967,2022-12-01,2022-12-31,30,county,5,1185,f,"Madison County, KY",NaN,Kentucky,KY,Multi-Family (2-4 Unit),4,266750.0,0.056436,-0.170112,253500.0,-0.043396,0.056470,89.394144,-0.076517,-0.278014,144.444444,0.028378,0.039874,4.0,0.000000,-0.600000,1.0,-0.875000,-0.916667,3.0,-0.571429,-0.700000,3.0,0.500000,2.000000,0.8,0.3,0.7,12.0,-58.0,-171.0,0.983906,-0.004270,-0.007812,0.500000,0.500000,0.500000,0.666667,NaN,NaN,0.000000,-0.750000,-0.916667,"Richmond, KY",40080.0,2023-04-09 14:55:08
117968,2022-09-01,2022-09-30,30,county,5,2899,f,"Davis County, UT",NaN,Utah,UT,Multi-Family (2-4 Unit),4,552000.0,-0.283117,-0.157252,514900.0,-0.009712,0.072708,257.464789,0.346173,0.265749,216.417910,-0.030007,0.053633,3.0,0.000000,-0.571429,1.0,-0.800000,-0.800000,1.0,-0.800000,-0.800000,6.0,0.000000,0.200000,2.0,0.0,1.3,29.0,-10.0,2.0,0.970678,-0.012586,0.016162,0.333333,0.333333,0.333333,0.500000,0.333333,0.300000,0.000000,-0.200000,-0.600000,"Ogden, UT",36260.0,2023-04-09 14:55:08

In [47]:
df = df_copy.loc[:, ['period_begin', 'region', 'state', 'state_code', 'property_type', 'homes_sold', 'new_listings', 'inventory', 'median_dom', 'months_of_supply', 'avg_sale_to_list', 'last_updated']]

In [48]:
df = df.sort_values(by='period_begin', ascending=False)
df = df.reset_index(drop=True)
df = df.rename(columns={'region':'county', 'period_begin': 'month'})
df

,month,county,state,state_code,property_type,homes_sold,new_listings,inventory,median_dom,months_of_supply,avg_sale_to_list,last_updated
0,2023-03-01,"Plymouth County, IA",Iowa,IA,All Residential,3.0,13.0,17.0,12.0,5.7,1.017140,2023-04-09 14:55:08
1,2023-03-01,"Sullivan County, NY",New York,NY,Multi-Family (2-4 Unit),4.0,4.0,11.0,103.0,2.8,0.936421,2023-04-09 14:55:08
2,2023-03-01,"Washington County, CO",Colorado,CO,Single Family Residential,7.0,2.0,11.0,157.0,1.6,0.953884,2023-04-09 14:55:08
3,2023-03-01,"Decatur County, TN",Tennessee,TN,Single Family Residential,8.0,14.0,41.0,66.0,5.1,0.897618,2023-04-09 14:55:08
4,2023-03-01,"Somerset County, NJ",New Jersey,NJ,Single Family Residential,230.0,240.0,296.0,22.0,1.3,1.016352,2023-04-09 14:55:08
...,...,...,...,...,...,...,...,...,...,...,...,...
117964,2022-01-01,"Madison County, MO",Missouri,MO,All Residential,13.0,14.0,24.0,77.0,1.8,0.944636,2023-04-09 14:55:08
117965,2022-01-01,"Christian County, KY",Kentucky,KY,Single Family Residential,37.0,28.0,47.0,53.0,1.3,0.991711,2023-04-09 14:55:08
117966,2022-01-01,"Ada County, ID",Idaho,ID,All Residential,711.0,739.0,760.0,28.0,1.1,0.995313,2023-04-09 14:55:08
117967,2022-01-01,"Montgomery County, TN",Tennessee,TN,Condo/Co-op,13.0,19.0,43.0,58.0,3.3,0.992386,2023-04-09 14:55:08
117968,2022-01-01,"Larimer County, CO",Colorado,CO,Single Family Residential,279.0,295.0,412.0,37.0,1.5,1.013137,2023-04-09 14:55:08

In [49]:
# Convert the 'month' column to a datetime object
df['month'] = pd.to_datetime(df['month'])
df['county_name'] = df['county'].apply(lambda x: x.split(',')[0] if ',' in x else x)

filtered_df = df[df['month'] >= '2022-01-01']
df_residential = filtered_df[filtered_df['property_type'] == 'All Residential']

df_residential

,month,county,state,state_code,property_type,homes_sold,new_listings,inventory,median_dom,months_of_supply,avg_sale_to_list,last_updated,county_name
0,2023-03-01,"Plymouth County, IA",Iowa,IA,All Residential,3.0,13.0,17.0,12.0,5.7,1.017140,2023-04-09 14:55:08,Plymouth County
6,2023-03-01,"Cumberland County, IL",Illinois,IL,All Residential,4.0,5.0,13.0,15.0,3.3,1.028047,2023-04-09 14:55:08,Cumberland County
10,2023-03-01,"Moore County, NC",North Carolina,NC,All Residential,209.0,217.0,244.0,29.0,1.2,0.992340,2023-04-09 14:55:08,Moore County
11,2023-03-01,"Plymouth County, MA",Massachusetts,MA,All Residential,327.0,552.0,638.0,29.0,2.0,0.998781,2023-04-09 14:55:08,Plymouth County
12,2023-03-01,"Cole County, MO",Missouri,MO,All Residential,60.0,67.0,67.0,8.0,1.1,1.000707,2023-04-09 14:55:08,Cole County
...,...,...,...,...,...,...,...,...,...,...,...,...,...
117957,2022-01-01,"Hancock County, ME",Maine,ME,All Residential,67.0,25.0,106.0,40.0,1.6,0.964497,2023-04-09 14:55:08,Hancock County
117961,2022-01-01,"Sullivan County, NH",New Hampshire,NH,All Residential,34.0,23.0,83.0,63.0,2.4,1.005345,2023-04-09 14:55:08,Sullivan County
117963,2022-01-01,"Pecos County, TX",Texas,TX,All Residential,2.0,9.0,43.0,61.0,21.5,NaN,2023-04-09 14:55:08,Pecos County
117964,2022-01-01,"Madison County, MO",Missouri,MO,All Residential,13.0,14.0,24.0,77.0,1.8,0.944636,2023-04-09 14:55:08,Madison County
117966,2022-01-01,"Ada County, ID",Idaho,ID,All Residential,711.0,739.0,760.0,28.0,1.1,0.995313,2023-04-09 14:55:08,Ada County

In [52]:

df = df_residential.copy()

In [55]:
# Drop the 'county' and 'state' columns
df = df.drop(columns=['county', 'state'])

# Rearrange the columns
df = df[['month', 'county_name', 'state_code', 'property_type', 'homes_sold', 'new_listings', 'inventory', 
         'median_dom', 'months_of_supply', 'avg_sale_to_list', 'last_updated']]

df = df.sort_values(by=['state_code', 'county_name', 'month'])

df

KeyError: "['county', 'state'] not found in axis"

In [54]:
# Get today's date
today = datetime.date.today()
date_string = today.strftime("%Y-%m-%d")
file_path = f"data/redfin_processed_output_{date_string}.csv"
df.to_csv(file_path, index=False)